### ISSUE TITLE
Update this guide to use Jaeger 

### ISSUE THREAD

**Issue by Emily-Jiang** [OpenLiberty/guide-microprofile-opentracing#101]
The feature mpOpenTracing-1.3 offers the support of Jaeger without the need to install user feature. Please update this guide to demonstrate the improvement.

**Comment by yeekangc** [comment]
This maps to this PR, https://github.com/OpenLiberty/guide-microprofile-opentracing/pull/94, and https://github.com/OpenLiberty/guides-common/issues/360 in the backlog.

**Comment by gkwan-ibm** [comment]
@yeekangc, SME suggested to have a separated guide for Jaeger or this guide shows both zipkin and Jaeger. I will go for a separated guide.

@fmhwong^

**Comment by yeekangc** [comment]
Let us introduce a separate guide for MP Open Tracing with Jaeger.  Thank you.

**Comment by k-rtik** [comment]
MP Open Tracing with Jaeger: https://github.com/OpenLiberty/draft-guide-microprofile-opentracing-jaeger

**Comment by gkwan-ibm** [comment]
dup of https://github.com/OpenLiberty/guides-common/issues/360

**Comment by gkwan-ibm** [comment]
A new guide "Enabling distributed tracing in microservices with Jaeger" was published at https://openliberty.io/guides/microprofile-opentracing-jaeger.html
