### ISSUE TITLE
OpenTracing: Show screen captures of traces

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/guide-microprofile-opentracing#11]
It will be nice if we can show screen captures of the traces as opposed to listing the spans only.  We ran into display issue on the website for this.

@Kubik42, let us work with @steven1046 and @kinueng to see what needs to be done so we can show pictures properly on the website in the guides.

**Comment by Kubik42** [comment]
Ok sounds good. Just to summup, the pictures display just fine on the website, but because they are so long, they end up being very small and difficult to see. Perhaps there can be a way to enlarge them when clicked?

**Comment by Kubik42** [comment]
just fyi, the screencaptures can be found under the `resource` directory in the `screencaptures` branch

**Comment by kinueng** [comment]
The idea of enlarging images when they are click sounds appealing.  If we enabled enlarge on click, most likely that functionality would apply to all blog/guide/intro doc images.

**Comment by evelinec** [comment]
Move this one back to backlog for now.

**Comment by gkwan-ibm** [comment]
close
- this guide is stabilized, i.e. not change anymore
- will direct users to a new guide for mp-opentelemetry
