### ISSUE TITLE
Update to use Open Tracing 2.0

### ISSUE THREAD

**Issue by Emily-Jiang** [OpenLiberty/guide-microprofile-opentracing#127]

**Comment by gkwan-ibm** [comment]
After I read the UFO, I found to update [the existing guide](https://openliberty.io/guides/microprofile-opentracing.html) for the MP OpenTracing with following: 
- update server.xml to mpOpenTracing-2.0
- update to user feature 0.33
- Span need to call finish()
- use new APIs
- better to use new LMP and use LMP to install user feature

@fmhwong If you have different opinion or more thing to add, would you let us know?

**Comment by gkwan-ibm** [comment]
@fmhwong I don't think the[ opentracing-jaeger ](https://openliberty.io/guides/microprofile-opentracing-jaeger.html)guide need to update anything except align with using  mpOpenTracing-2.0 in server.xml, right?

**Comment by fmhwong** [comment]
Yes, you do.  You need to migrate OpenTracing API from 0.31 to 0.33.  For example, https://github.com/OpenLiberty/guide-microprofile-opentracing/blob/d9f96218014676240bcf60a82fb8f20de01763ee/finish/inventory/src/main/java/io/openliberty/guides/inventory/InventoryManager.java#L59

**Comment by gkwan-ibm** [comment]
close
- both guide-microprofile-opentracing and guide-microprofile-opentracing-jaeger were updated
