### ISSUE TITLE
Add a reference to the new MicroProfile Telemetry 1.0 specification

### ISSUE THREAD

**Issue by fmhwong** [OpenLiberty/guide-microprofile-opentracing#163]
When MicroProfile 6.0 is GAed in OpenLiberty, the following should be added to this guide.

A new MicroProfile Telemetry 1.0 specification is available in MicroProfile 6.0 specification.  MicroProfile OpenTracing 3.0 specification will be stabilized.  OpenLiberty version X will provide an implementation of MicroProfile 6.0 specification.  The MicroProfile Telemetry feature name is `mpTelemetry-1.0`.

**Comment by gkwan-ibm** [comment]
close
- this guide was deprecated from the ol.io site.
- There is a message at the banner to point users to check out the [microprofile-telemetry-jaeger guide](https://openliberty.io/guides/microprofile-telemetry-jaeger.html)
- It is not a practice to announce the spec change in the guide. Instead, it is mentioned in the ol.io [Docs](https://openliberty.io/docs/latest/reference/diff/mp-50-60-diff.html#telemetry)
