### ISSUE TITLE
Hello there! I would like to contribute to this work by translating it to Spanish which is my native language. 

### ISSUE THREAD

**Issue by LuigiBaute** [OpenLiberty/guide-microprofile-opentracing#2]

**Comment by Kubik42** [comment]
Hi! Thank you for your offer, but translating the guides requires ID reviews. Meaning, we would have to get someone internal (who speaks Spanish) in touch with you to make sure the language and formatting meets our standards. This is not plausible at the moment

**Comment by LuigiBaute** [comment]
@Kubik42 have you tought about it?

**Comment by yeekangc** [comment]
@LuigiBaute, thank you.  We are looking into this and will get back to you as soon as possible.

**Comment by yeekangc** [comment]
@LuigiBaute, if you are still interested, we are happy to work with you further.

A simple starting point will be to take our README.adoc and translate it into Spanish, then submit a PR for README-es.adoc.

Please let us know.
