### ISSUE TITLE
Unresolved directive in README.adoc "mvnpackage.adoc"

### ISSUE THREAD

**Issue by apupier** [OpenLiberty/guide-microprofile-opentracing#20]
Unresolved directive in README.adoc - include::https://raw.githubusercontent.com/OpenLiberty/guides-common/master/mvnpackage.adoc[]

![image](https://user-images.githubusercontent.com/1105127/41297074-a05d3b56-6e5e-11e8-859a-f64ea65f3fea.png)

**Comment by Kubik42** [comment]
Should be fixed now. The site just didn't refresh in time:

<img width="837" alt="screen shot 2018-06-25 at 1 14 40 pm" src="https://user-images.githubusercontent.com/11563877/41865003-cad49288-7879-11e8-9086-323cea34b55b.png">

**Comment by Kubik42** [comment]
Feel free to close @apupier
