### ISSUE TITLE
Use of ActiveSpan from io.opentracing won't work with mpOpenTracing-1.1

### ISSUE THREAD

**Issue by jwalcorn** [OpenLiberty/guide-microprofile-opentracing#40]
When mpOpenTracing-1.1 is released as part of microProfile-1.4 in Liberty 18.0.0.3 at the end of the quarter, it will be moving up to a new level of the io.opentracing prerequisite.  Unfortunately, there are breaking API changes in that new 0.31 level, such as the io.opentracing.ActiveSpan API going away (apparently to be replaced by a new io.opentracing.Scope API).  We'll need to update our Open Tracing guide, which currently shows usage of that ActiveSpan API, to work once people move up to MP 1.4 (or MP 2.0).  The current code will neither compile nor run at that point.  These changes were discussed in the recent WAD review for MP OpenTracing 1.1.

**Comment by Kubik42** [comment]
Thanks for the heads up @jwalcorn! Do you now if the zipkin user feature will be moving up as well (this one here https://github.com/WASdev/sample.opentracing.zipkintracer)? To make sure everything works before the 18003 release, I'll need a 18003 build with all the OpenTracing-1.1 tracing changes (which I believe I already have) and the new zipkin user feature for opentracing-0.31, which I currently do not have.

**Comment by Kubik42** [comment]
Found this, which seems to summarize the changes pretty well: https://medium.com/opentracing/announcing-java-v0-31-release-candidate-6e1f1a922d2e

**Comment by Kubik42** [comment]
See #43 for the changes.

**Comment by evelinec** [comment]
Tagging @gkwan-ibm to review and follow up when new version is ready.

**Comment by gkwan-ibm** [comment]
close
- this guide is stabilized, i.e. not change anymore
- will direct users to a new guide for mp-opentelemetry
