### ISSUE TITLE
"This This page isn’t working" when accessing system/properties endpoint

### ISSUE THREAD

**Issue by andrewdes** [OpenLiberty/guide-microprofile-opentracing#45]
When following the guide instructions and running `mvn install` followed by `mvn liberty:start-server` everything works as intended and all endpoints are accessible without running into "This page isn’t working".

However, if you attempt to run this in one command `mvn install liberty:start-server` the build is successful but you are faced with "This page isn’t working" when navigating to http://localhost:9080/system/properties and http://localhost:9081/inventory/systems/localhost (http://localhost:9081/inventory/systems works fine). 

I believe this has something to do with the maven profile in the `inventory/pom.xml` that navigates to the `system` directory and executes a `liberty:stop-server` command after the tests. Since the `console.log` in the `system` directory shows that the server has been stopped.

Although this only happens when running `mvn install liberty:start-server` even though the guide instructs you to run `mvn install` followed by `mvn liberty:start-server`, I still think this should be fixed or at least noted somewhere.

**Comment by gkwan-ibm** [comment]
dup #58
