### ISSUE TITLE
Multipane Issues

### ISSUE THREAD

**Issue by justineechen** [OpenLiberty/guide-microprofile-opentracing#49]
- [ ] mvn commands under `Running the services` are not displaying correctly 
- [x] add quiet flag to .travis.yml
- [ ] update pom files in finish and start
- [ ] format files

**Comment by justineechen** [comment]
https://github.com/OpenLiberty/openliberty.io/issues/849

**Comment by Rachelwrq** [comment]
### Running the services
- [ ] mvn commands are not displayed correctly. Just need to add `[role='command']` above the `include::{common-includes}/mvncompile.adoc[]`.

### Enabling distributed tracing
#### Enabling explicit distributed tracing
- [ ] the first hotspot on `list()` doesn't highlight anything on the right
- [ ] `mvn compile` might be changed to role command?
- [ ] the second action arrow doesn't highlight anything

#### Injecting a custom Tracer object
- [ ] `mvn compile` might be changed to role command?

**Comment by Rachelwrq** [comment]
- [ ] Need guide attribution.
- [ ] End with "in Open Liberty" in the first sentence under "Nice work! You did it!"

**Comment by Rachelwrq** [comment]
### Checklist for Post-Review
**Through the browser:**
- [ ] Read through guide, making sure that the flow of the guide is good
- [ ] Click all links to make sure they lead to the correct place
- [ ] Make sure hotspots, code_commands and files are correct
- [ ] Run Acrolinx

**Comment by justineechen** [comment]
2nd round:
- [ ] guide author
- [ ] update to master
- [ ] mvn instructions
- [ ] if there is a clean comment, let consider or discuss it
- [ ] make sure liberty:stop-server before the testing (assumed testing is at the end)
- [ ] update the version of cxf-rt-rs-client and cxf-rt-rs-extension-providers to 3.2.6

**Comment by gkwan-ibm** [comment]
- completed the first round of pre-publishing test
- most of the issues were addressed
- rest-hatoes guide was fixed
- 5 guides were blocked 
- we will start the second around of pre-publishing test and as well as to figure out the blockers
