### ISSUE TITLE
HTTP call chain "inventory-service -> system-service" is not shown in Zipkin because X-B3-TraceId header is not passed

### ISSUE THREAD

**Issue by progaddict** [OpenLiberty/guide-microprofile-opentracing#53]
### Steps to reproduce
* `git clone git@github.com:OpenLiberty/guide-microprofile-opentracing.git`
* `cd guide-microprofile-opentracing/finish`
* `docker run -d -p 9411:9411 openzipkin/zipkin # start zipkin`
* `mvn clean package -DskipTests=true`
* `mvn liberty:start-server`
* go to `http://localhost:9081/inventory/systems/localhost` and observe the system properties
* go to `http://localhost:9411/zipkin/` and observe that there are 2 separate traces: one for `inventory-service` and the other one for `system-service`

### Expected behaviour
There should be one trace with 3 spans:
* inventory-service (HTTP GET http://localhost:9081/inventory/systems/localhost)
* system-service (HTTP GET http://localhost:9080/system/properties)
* inventory service (the custom "add() span")

The trace corresponds to the HTTP call chain: `browser -> inventory-service -> system-service`.

Exported Zipkin trace:
```json
[
  {
    "traceId": "442f8f2b640a3b91",
    "parentId": "442f8f2b640a3b91",
    "id": "469fa65b9666f6f7",
    "kind": "CLIENT",
    "name": "get",
    "timestamp": 1548690186290695,
    "duration": 1263733,
    "localEndpoint": {
      "serviceName": "inventory-service",
      "ipv4": "10.2.1.199"
    },
    "tags": {
      "component": "jaxrs",
      "http.method": "GET",
      "http.status_code": "200",
      "http.url": "http://localhost:9080/system/properties"
    }
  },
  {
    "traceId": "442f8f2b640a3b91",
    "parentId": "442f8f2b640a3b91",
    "id": "5c5d81cbe615a799",
    "name": "add() span",
    "timestamp": 1548690187664661,
    "duration": 37,
    "localEndpoint": {
      "serviceName": "inventory-service",
      "ipv4": "10.2.1.199"
    }
  },
  {
    "traceId": "442f8f2b640a3b91",
    "id": "442f8f2b640a3b91",
    "kind": "SERVER",
    "name": "get:io.openliberty.guides.inventory.inventoryresource.getpropertiesforhost",
    "timestamp": 1548690186090562,
    "duration": 1577685,
    "localEndpoint": {
      "serviceName": "inventory-service",
      "ipv4": "10.2.1.199"
    },
    "tags": {
      "component": "jaxrs",
      "http.method": "GET",
      "http.status_code": "200",
      "http.url": "http://localhost:9081/inventory/systems/localhost"
    }
  },
  {
    "traceId": "442f8f2b640a3b91",
    "parentId": "442f8f2b640a3b91",
    "id": "469fa65b9666f6f7",
    "kind": "SERVER",
    "name": "get:io.openliberty.guides.system.systemresource.getproperties",
    "timestamp": 1548690187372357,
    "duration": 56674,
    "localEndpoint": {
      "serviceName": "system-service",
      "ipv4": "10.2.1.199"
    },
    "tags": {
      "component": "jaxrs",
      "http.method": "GET",
      "http.status_code": "200",
      "http.url": "http://localhost:9080/system/properties"
    },
    "shared": true
  }
]
```

### Quick and dirty fix (see the `getProperties` and not the `getProperties2` method):
```java
package io.openliberty.guides.inventory;

import java.net.URL;
import java.net.UnknownHostException;
import java.net.MalformedURLException;
import javax.ws.rs.ProcessingException;
import javax.ws.rs.client.ClientBuilder;
import java.util.Properties;
import org.apache.commons.lang3.exception.ExceptionUtils;
import org.eclipse.microprofile.rest.client.RestClientBuilder;
import io.openliberty.guides.inventory.client.SystemClient;
import io.openliberty.guides.inventory.client.UnknownUrlException;
import io.openliberty.guides.inventory.client.UnknownUrlExceptionMapper;

public class InventoryUtils {

  private final String SYSTEM_PORT = System.getProperty("system.http.port");
  
    public Properties getProperties2(String hostname) {
        try {
            String customUrlString = "http://" + hostname + ":" + SYSTEM_PORT + "/system";
            URL customURL = new URL(customUrlString);
            SystemClient customRestClient = RestClientBuilder.newBuilder()
                                                             .baseUrl(customURL)
                                                             .register(UnknownUrlExceptionMapper.class)
                                                             .build(SystemClient.class);
            return customRestClient.getProperties();
        } catch (ProcessingException ex) {
            handleProcessingException(ex);
        } catch (UnknownUrlException ex) {
            System.err.println("The given URL is unreachable.");
        } catch (MalformedURLException ex) {
            System.err.println("The given URL is not formatted correctly: " + ex.getMessage());
        }
        return null;
    }

    public Properties getProperties(String hostname) {
        String customUrlString = "http://" + hostname + ":" + SYSTEM_PORT + "/system/properties";
        return ClientBuilder.newClient().target(customUrlString).request().get(Properties.class);
    }

    public void handleProcessingException(ProcessingException ex) {
        Throwable rootEx = ExceptionUtils.getRootCause(ex);
        if (rootEx != null && rootEx instanceof UnknownHostException) {
            System.err.println("The specified host is unknown: " + ex.getMessage());
        } else {
            throw ex;
        }
    }
}

```

### Notes
The Open Tracing spec (1.2.1, November 13, 2018) says the following:
> 3.1.3. Span creation and injection for outbound requests
> Tracing in javax.ws.rs.client.Client has to be explicitly enabled by
org.eclipse.microprofile.opentracing.ClientTracingRegistrar.configure(ClientBuilder
invoking
clientBuilder). The implementation might enable client tracing globally, in this case explicit
configuration has no effect.
> When a request is sent from a JAX-RS javax.ws.rs.client.Client, a new Span is created and its SpanContext is injected in the outbound request for propagation downstream. The new Span will be a child of the active Span if an active Span exists. The new Span will be finished when the
outbound request is completed.
> [...]

And the current guide's code uses the MicroProfile's REST Client (i.e. `RestClientBuilder` and friends) which seems not yet to be integrated with the Open Tracing mechanism.

**Comment by progaddict** [comment]
The reason that Zipkin is not able to relate the traces is that the `X-B3-TraceId` header (as well as other `X-B3-*` headers) is not propagated further during the HTTP call to the `system-service`.

The headers should be propagated like this:
```
GET http://localhost:9080/system/properties HTTP/1.1
Accept: */*
X-B3-TraceId: 442f8f2b640a3b91
X-B3-SpanId: 469fa65b9666f6f7
X-B3-ParentSpanId: 442f8f2b640a3b91
X-B3-Sampled: 1
User-Agent: Apache-CXF/3.2.6
Cache-Control: no-cache
Pragma: no-cache
Proxy-Connection: keep-alive
Host: localhost:9080
```

However the REST client (which is built via `RestClientBuilder`) does not do that out-of-the-box.

**Comment by yeekangc** [comment]
@andymc12 @donbourne @fmhwong

**Comment by fmhwong** [comment]
To use MicroProfile OpenTracing and REST Client, you will need to have MicroProfile OpenTracing 1.3 and REST Client 1.2.

**Comment by progaddict** [comment]
> To use MicroProfile OpenTracing and REST Client, you will need to have MicroProfile OpenTracing 1.3 and REST Client 1.2.

...which have not yet been implemented for open liberty:
https://search.maven.org/search?q=g:io.openliberty.features%20mpOpenTracing
:smiley:

**Comment by fmhwong** [comment]
> > To use MicroProfile OpenTracing and REST Client, you will need to have MicroProfile OpenTracing 1.3 and REST Client 1.2.
> 
> ...which have not yet been implemented for open liberty:
> https://search.maven.org/search?q=g:io.openliberty.features%20mpOpenTracing
> 😃

That is correct.  @yeekangc You might want to revise the guide.

**Comment by yeekangc** [comment]
Yes, this is a miss on our part.  Good catch and thank you, @progaddict.

We are working on a fix and will push ASAP.  Will move back to REST Client when the support is there.

@gkwan-ibm @evelinec

**Comment by progaddict** [comment]
you are welcome, @yeekangc  :+1: 

by the way, I've found one more "bug":
https://github.com/OpenLiberty/guide-microprofile-jwt/issues/86
:smiley: 

However, this is an inconsistency / configuration problem rather than a bug. I have found the documentation about mapping roles to groups but I haven't found a way to map MP-JWT's group to the built-in "Administrator" security role. It seems that open liberty maps groups to roles and then roles to MP-JWT's groups but not the other way around.

It would be great though if one would not need to do that at all but rather could configure the allowed roles right in the `<mpMetrics />` configuration element.

**Comment by justineechen** [comment]
It looks like the zipkin UI summary may have a bug it shows 4 spans instead of 3 on the first summary page:
<img width="1663" alt="screen shot 2019-01-30 at 3 55 22 pm" src="https://user-images.githubusercontent.com/18709242/52067802-5e831500-2549-11e9-9c6c-c62ad9000f79.png">
<img width="1650" alt="screen shot 2019-01-30 at 3 55 29 pm" src="https://user-images.githubusercontent.com/18709242/52067804-5fb44200-2549-11e9-9e0e-48b92cd47c2a.png">

**Comment by progaddict** [comment]
hi @justineechen 
thank you for looking into this issue.

Zipkin may have this bug indeed.
However, independently of the fact whether Zipkin has this bug or not, open liberty (OL) should pass the `X-B3-*` opentracing headers further down the HTTP call chain.

You can check that by placing a HTTP proxy (e.g. ZAP proxy) between inventory service and system service:
```xml
            <plugin>
                <groupId>net.wasdev.wlp.maven.plugins</groupId>
                <artifactId>liberty-maven-plugin</artifactId>
                <version>2.6.1</version>
                <configuration>
                    <assemblyArtifact>
                        <groupId>io.openliberty</groupId>
                        <artifactId>openliberty-runtime</artifactId>
                        <version>${version.openliberty-runtime}</version>
                        <type>zip</type>
                    </assemblyArtifact>
                    <configFile>src/main/liberty/config/server.xml</configFile>
                    <include>usr</include>
                    <bootstrapProperties>
                        <default.http.port>${inv.service.http.port}</default.http.port>
                        <default.https.port>${inv.service.https.port}</default.https.port>
                        <system.http.port>${sys.service.http.port}</system.http.port>
                    </bootstrapProperties>
                    <jvmOptions>
                        <param>-Dhttp.proxyHost=localhost</param>
                        <param>-Dhttp.proxyPort=8080</param>
                    </jvmOptions>
                </configuration>
                ... further plugin configuration ...
            </plugin>
```

When I did that, I've noticed that OL does not do that when the `org.eclipse.microprofile.rest.client.RestClientBuilder` is used.
However if you switch to `javax.ws.rs.client.ClientBuilder` (which does not have the strong typing support as the RestClientBuilder) then you'll notice that the headers are passed further. The next service in the HTTP call chain recognizes then that the incoming HTTP request is part of an existing trace.

So the problem is that the new MP's strongly typed `RestClientBuilder` is not integrated with JAX RS runtime and therefore it is not aware that the current request has the opentracing headers in it which need to be copied over to a new request.

You might want to consider adding an integration test for this use case e.g. using the [Citrus Integration Testing Framework](https://github.com/citrusframework/citrus). Or hire us ([ConSol Software GmbH](https://github.com/consol)) and we'll do that for you :smiley:

**Comment by progaddict** [comment]
when talking about the integration test, I meant the OL project of course and not the guide.
it would be an overkill for a guide.

**Comment by justineechen** [comment]
@progaddict Thank you for letting us know about this issue and checking out our guides! :) 
I've reverted the guide back to using the SystemClient here: https://github.com/OpenLiberty/guide-microprofile-opentracing/pull/55

The guide should now show the original 3 spans for 1 trace

**Comment by progaddict** [comment]
thank you guys for a quick response!
