### ISSUE TITLE
Failed to run the guide end to end

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guide-microprofile-opentracing#58]
- [ ] `mvn install liberty:start-server` failed
- [ ] `mvn install` does not stop system service
- [x] started servers at the start directory, following urls return "Context Root Not Found"
  - http://localhost:9081/inventory/systems/localhost
   - http://localhost:9080/system/properties
   - http://localhost:9081/inventory/systems
- [x] at start directory, failed to run `mvn compile`
- [x] until replace InventoryManager class, mvn compile can be run successfully, but urls still return "Context Root Not Found"

**Comment by Azquelt** [comment]
This problem hit several people in our workshop.

When testing the `finish` project, you need to run `mvn install` and `mvn liberty:start-server` as separate commands. If you run `mvn install liberty:start-server`, it seems to start a server for the top-level project (which has no app or server config) on port 8080 which then causes the test for the system service to fail.

Can we fix this? It's very unintuitive when the user has done several guides already and is used to running `mvn install liberty:start-server`

**Comment by gkwan-ibm** [comment]
This issue should happen in this guide but not other guides. The workaround is to run `install` and `liberty:start-server` separately. It will be fixed soon.

**Comment by gkwan-ibm** [comment]
After investigation, the pom.xml files of this guide cannot support `mvn install liberty:start-server` at the parent directory. Both goals have to be run separately. Because this guide will be converted to use the new liberty maven plugin 3.x and development mode, this issue will not be fixed.

**Comment by Azquelt** [comment]
That makes sense, I was wondering if the guides would be updated to use development mode. Hopefully that will also make it less likely that users accidentally leave the server running.

**Comment by gkwan-ibm** [comment]
https://github.com/OpenLiberty/guides-common/issues/360

**Comment by gkwan-ibm** [comment]
close
- this guide is stabilized, i.e. not change anymore
- will direct users to a new guide for mp-opentelemetry
