### ISSUE TITLE
mvn install failing

### ISSUE THREAD

**Issue by fachat** [OpenLiberty/guide-microprofile-opentracing#61]
Just cloned the repo to local, cleaned the maven repo so everything is downloaded into a clean maven, and "mvn install" fails when it runs the test:

[ERROR] Failures: 
[ERROR]   SystemEndpointTest.testGetProperties:41 Incorrect response code from http://localhost:9080/ expected:<200> but was:<404>

This is on ubuntu 16.04 LTS with JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64

**Comment by fachat** [comment]
Arg, silly me. I guess there was another liberty running in the background that not got stopped. 

On the other hand, the error message is misleading.

**Comment by yeekangc** [comment]
Glad to hear that you worked it out, @fachat.  And, thank you for reporting the issue.

We do have this issue, https://github.com/OpenLiberty/guides-common/issues/157, in our backlog to see how we can make this better.  Feel free to track it and thank you again.
