### ISSUE TITLE
Improve Zipkin install instructions

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/guide-microprofile-opentracing#75]
It's unclear based on current instructions what you should do if you need to install Zipkin:

```
For this guide, use Zipkin as your distributed tracing system. You can find the installation instructions for Zipkin at the Zipkin quickstart page. You are not required to use Zipkin, but keep in mind that you might need more instructions that are not listed here if you choose to use another tracing system.

Before you proceed, make sure that your Zipkin server is up and running. By default, Zipkin can be found at the http://localhost:9411 URL.
```

We need to improve this.  For instance, suggest to users that if they have Docker, they can use that to get a Zipkin instance.  Clarify that a distributed tracing server is required too.

Tagging @fmhwong for additional thoughts.

**Comment by gkwan-ibm** [comment]
@fmhwong we would like to use Zipkin docker instead of user feature `<feature>usr:opentracingZipkin-0.31</feature>` and download by `download-maven-plugin`. Do you have any concern?

cc @jj-zhang, fyi

**Comment by gkwan-ibm** [comment]
close
- this guide is stabilized, i.e. not change anymore
- will direct users to a new guide for mp-opentelemetry
