### ISSUE TITLE
Review feedback

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/guide-microprofile-opentracing#8]
- I wonder if we should use "JAX-RS and non-JAX-RS methods" in the abstract and the 1st sentence or there is better alternative.  Just a thought.

- _MicroProfile OpenTracing enables distributed tracing in MicroProfile applications without adding any explicit distributed tracing code to the application._ Consider a different term than "MicroProfile applications".

- Update to use common includes and point to the proper repo etc before publishing.

- It will be better if we can use screen captures.  Let us work with openliberty.io team to see how we can get them displayed nicely?  This can be handled as a separate issue for the next round.

- Running the services:  Can we explain why we need to start and run the services first?

- _ the install and liberty:start-server Maven goals:_ Should be "the Maven install and liberty ... goals"

- _This user feature also comes with the opentracing-1.0 feature, so you don’t need to enable it explicitly._ I don't think we need to mention this?  And, it is not so much that it comes with the feature but the user feature requires it and will enable it automatically?

- We should reference OL docs instead of KC when it is available.  Create an issue for future.

- _The opentracing-1.0 OpenTracing feature found inside Open Liberty enables tracing of all JAX-RS methods by default_ I will focus on mpOpenTracing-1.0 and avoid references to opentracing-1.0, which can confuse people?  mpOpenTracing-1.0 handles all the details (internal dependencies) anyway.

- "Tweaks":  We don't do this in other guides but it may be alright here.  It will be good if we can highlight what you should tweak (certainly with the new 2-pane design).

- "MicroProfile Open Tracing specification":  Be careful with the distinction between the specification itself or the implementation of the specification in Open Liberty i.e. the mpOpenTracing feature or capability in OL.  Please review the usages of this term.

- Call out which part is for non-JAX-RS methods clearly.  We talked about this in the beginning so we should call it out clearly and refer to it at the right spot.

- Testing the services:  I will take away _No explicit tests exist to verify the correctness of the traces._ and lead with the instruction asking users to manually verify what is needed.  Then, refer to the automated tests included to test the endpoints.

- _which tracers are delivered to Zipkin._ Tracers or traces? I'd refer to OL here too?

**Comment by yeekangc** [comment]
@Kubik42, 1 more thing:  "In a real development environment" should be something like "in real world usage" since this is not only for "development".

**Comment by Kubik42** [comment]
All items addressed. See https://github.com/OpenLiberty/guide-microprofile-opentracing/pull/9/files

**Comment by yeekangc** [comment]
We can close after everything is merged.

**Comment by Kubik42** [comment]
Everything merged, closing...
