### ISSUE TITLE
Why do you need to import "io.opentracing.Tracer" into the InventoryManager class?

### ISSUE THREAD

**Issue by thomassuedbroecker** [OpenLiberty/guide-microprofile-opentracing#80]
Why do you need to import "io.opentracing.Tracer" into the InventoryManager class?

I notice following imports in InventoryManager.java.

```
import io.opentracing.Scope;
import io.opentracing.Tracer;
import io.openliberty.guides.inventory.model.*;
```
I notice the reason: https://youtu.be/s5nJqMOFhyE?t=1738

But with these imports, I need to add these dependencies to my pom.xml:

```
<dependency>
			<groupId>io.opentracing</groupId>
			<artifactId>opentracing-api</artifactId>
			<version>0.31.0</version>
</dependency>  
```
Why do you not need to add that in your pom.xml?

**Comment by yeekangc** [comment]
There is a custom tracer that is described at https://openliberty.io/guides/microprofile-opentracing.html#injecting-a-custom-tracer-object.

Is that what you are asking about, @thomassuedbroecker?

**Comment by thomassuedbroecker** [comment]
That question on github is only about: Why does the code of the sample work, even when you don‘t add the same dependencies I needed to add in my pom file for open tracing classes?
But that s not really important and we can close that topic.

**Comment by gkwan-ibm** [comment]
The sample inventory project includes the Liberty mpOpenTracing-1.3 feature as a dependency, and the Liberty maven plugin can resolve the app by all the dependencies of mpOpenTracing-1.3 feature. 
```
        <dependency>
            <groupId>io.openliberty.features</groupId>
            <artifactId>mpOpenTracing-1.3</artifactId>
            <type>esa</type>
       </dependency>
```

@thomassuedbroecker Hope it can answer your question.
